PANTONE_COLOR_BOOKS = [
    "PANTONE Color Bridge Coated-V4",
    "PANTONE Color Bridge Uncoated-V4",
    "PANTONE FHI Cotton TCX",
    "PANTONE FHI Metallic Shimmers TPM",
    "PANTONE FHI Nylon Brights TN",
    "PANTONE FHI Paper TPG",
    "PANTONE FHI Polyester TSX",
    "PANTONE Skin Tone Guide",
    "PANTONE solid coated",
    "PANTONE solid uncoated",
    "PANTONE+ Extended Gamut Coated",
    "PANTONE+ Metallic Coated",
    "PANTONE+ Pastels _Neons Coated",
    "PANTONE+ Pastels _Neons Uncoated",
    "PANTONE+ Premium Metallics Coated",
    "PANTONE+ Solid Coated",
    "PANTONE+ Solid Uncoated",
]